full screen gameplay, player score persists
reparadocs/iogame pull request #3
Opened 2016-11-10 20:09 UTC by arteartemis

2016-12-01 22:11 UTC, reparadocs commented on public/js/Bullet.js
> +      0, 2*Math.PI);
nit: ')' on next line

2016-12-01 22:17 UTC, reparadocs requested changes
Overall good, needs some minor changes and fix merge conflict with the yarn file

2016-12-01 22:17 UTC, reparadocs commented on public/js/GameObject.js
> +      (Globals.widthRatio * this._width), (Globals.heightRatio * this._height));
Nit: ')' on next line

2016-12-01 22:17 UTC, reparadocs commented on public/js/Bullet.js
> +      0, 2*Math.PI);
Nit: ')' on next line

2016-12-01 22:17 UTC, reparadocs commented on public/js/Keys.js
> +		&& Math.abs(this._localPlayer.getY() * Globals.heightRatio - this._mouseY) < 15;
Nit: indent here

2016-12-01 22:17 UTC, reparadocs commented on public/js/Player.js
> +		var x_pos = this._x * Globals.widthRatio;
nit: use const instead of var

2016-12-01 22:17 UTC, reparadocs commented on public/js/Player.js
> +		var y_pos = this._y * Globals.heightRatio;
nit: use const instead of var

2016-12-01 22:17 UTC, reparadocs commented on public/js/Player.js
> +				y_pos + (size * Globals.widthRatio * this._shootDir[1]));
nit: ')' on next line

2016-12-01 22:17 UTC, reparadocs commented on public/js/Player.js
> +				y_pos + ((size * Globals.widthRatio - 5) * this._shootDir[1]));
nit: ')' on next line

2016-12-01 22:17 UTC, reparadocs commented on public/js/Player.js
> +			this._y * Globals.heightRatio + 5);
nit: ')' on next line

2016-12-01 22:17 UTC, reparadocs commented on public/js/Player.js
> +		//this._score = 0;
Remove it if not necessary (but why are we removing score?)

2016-12-01 22:17 UTC, reparadocs commented on public/js/Resource.js
> +      0, 2*Math.PI);
Nit ')' on next line

2016-12-01 22:17 UTC, reparadocs commented on public/js/game.js
> +	Constants.widthRatio = window.innerWidth / Constants.gameWidth;
If they're constants, they shouldn't change, put this in Globals

2016-12-01 22:17 UTC, reparadocs commented on public/js/game.js
> +	ctx.fillStyle = '#FFC0CB';
Put this color in Constants

2016-12-01 22:17 UTC, reparadocs commented on public/js/Bullet.js
> +      0, 2*Math.PI);
Also add a ',' after this line, and do this for every time you move the ')' down

2016-12-26 01:20 UTC, arteartemis commented on public/js/Player.js
> +		//this._score = 0;
we aren't removing it -- we're just not resetting the player's score in between deaths (score persists)

2016-12-30 23:56 UTC, reparadocs requested changes
really good overall, fix your editor's settings to change tabs to 2 spaces and reformat all the files (there should be a menu option that lets you easily reformat files with your new setting), and a few minor formatting nits

2016-12-30 23:56 UTC, reparadocs commented on public/js/ClientPlayer.js
> +  constructor(startX: number, startY: number, dir: Array<number>, color: string, name: string, createBullet: Function) {
Keep lines to width 80 max:

`
constructor(

    startX: number,
 
    startY: number, 

    dir: Array<number>,

    color: string, 

    name: string, 

    createBullet: Function,

  ) {
`

2016-12-30 23:56 UTC, reparadocs commented on public/js/Constants.js
> -
keep lines in between to differentiate different types of constants (resource constants are different than history constants, etc.)

2016-12-30 23:56 UTC, reparadocs commented on public/js/Constants.js
> +  adjectives: Array<string>,
name_prefix_adjectives might be more descriptive to reduce confusion in the future

2016-12-30 23:56 UTC, reparadocs commented on public/js/Constants.js
> +  animals: Array<string>,
name_suffix_animals might be more descriptive to reduce confusion in the future

2016-12-30 23:56 UTC, reparadocs commented on public/js/Constants.js
> +  animals: ['alligator', 'ant', 'antelope', 'bat', 'bear', 'beaver', 'bee', 'beetle',
would be better if you can figure out a way to pull this from a separate text file but if it takes too much effort, don't worry about it not a big deal

2016-12-30 23:56 UTC, reparadocs commented on public/js/Constants.js
> +  adjectives: ['incredible', 'awesome', 'amazing', 'marvelous', 'wonderful',
same as above

2016-12-30 23:56 UTC, reparadocs commented on public/js/Keys.js
> +			&& Math.abs(this._localPlayer.getY() * Globals.heightRatio - this._mouseY) < 15;
Hmm, check out your tabs... the settings should be converting tabs to spaces and set it to 2 spaces

2016-12-30 23:56 UTC, reparadocs commented on public/js/Player.js
> +	constructor(startX: number, startY: number, dir: Array<number>, color: string, name: string, createBullet: Function) {
try to limit to 80 characters/line

2016-12-30 23:56 UTC, reparadocs commented on public/js/Player.js
> +	_generateName(name: string) {
Check tabs again for this whole file

2016-12-30 23:56 UTC, reparadocs commented on public/js/Player.js
> +		if (!this._init_name) {
Hmm, why do you need __init__name? Can't you just check if this._name is null or something along those lines? Seems messy to have another bool for this

2016-12-30 23:56 UTC, reparadocs commented on public/js/game.js
> +    return b._score - a._score;
fix tabbing here

2016-12-30 23:56 UTC, reparadocs commented on public/js/game.js
> +		ctx.fillText(
Fix tabs-> 2 spaces formatting

2016-12-30 23:56 UTC, reparadocs commented on node_modules/.yarn-integrity
> -2e6bdee5b01093c3fb20daeaae838b7c24e86ee68a22f5a1670a583b61581bdf
Try to add the whole node_modules dir to .gitignore. If it takes you longer than 5 mins, lemme know and I'll do it

2017-01-10 04:11 UTC, merged